### ISSUE TITLE
gazebo2rviz error

### ISSUE THREAD

**Issue by 4-legends** [andreasBihlmaier/gazebo2rviz#11]
paresh@paresh-macbookpro:~$ roslaunch gazebo2rviz gazebo2rviz.launch
... logging to /home/paresh/.ros/log/c06cfaac-dfee-11e7-b9e5-90fd61edc49c/roslaunch-paresh-macbookpro-13477.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://paresh-macbookpro:34401/

SUMMARY
========

PARAMETERS
 * /gazebo2marker/ignore_submodels_of: 
 * /gazebo2tf/ignore_submodels_of: 
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES
  /
    gazebo2marker (gazebo2rviz/gazebo2marker_node.py)
    gazebo2tf (gazebo2rviz/gazebo2tf_node.py)
    static_tf_pub_world_to_gazebo_world (tf2_ros/static_transform_publisher)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[static_tf_pub_world_to_gazebo_world-1]: started with pid [13496]
process[gazebo2tf-2]: started with pid [13497]
process[gazebo2marker-3]: started with pid [13502]
[INFO] [1513160257.894341]: Ignoring submodels of: ['']
[INFO] [1513160257.902739]: Spinning
[INFO] [1513160257.993016]: Ignoring submodels of: ['']
Traceback (most recent call last):
  File "/home/paresh/catkin_ws/src/gazebo2rviz/scripts/gazebo2marker_node.py", line 94, in <module>
    main()
  File "/home/paresh/catkin_ws/src/gazebo2rviz/scripts/gazebo2marker_node.py", line 73, in main
    rospy.logerror('ignore_submodels_of is currently not supported and will thus have no effect')
AttributeError: 'module' object has no attribute 'logerror'
[gazebo2marker-3] process has died [pid 13502, exit code 1, cmd /home/paresh/catkin_ws/src/gazebo2rviz/scripts/gazebo2marker_node.py -f 2 __name:=gazebo2marker __log:=/home/paresh/.ros/log/c06cfaac-dfee-11e7-b9e5-90fd61edc49c/gazebo2marker-3.log].
log file: /home/paresh/.ros/log/c06cfaac-dfee-11e7-b9e5-90fd61edc49c/gazebo2marker-3*.log

**Comment by andreasBihlmaier** [comment]
Fixed by https://github.com/andreasBihlmaier/gazebo2rviz/commit/5d5e82274b742f02911136e47d2f0e02d986e89f
