### ISSUE TITLE
Support for worlds without sdf files?

### ISSUE THREAD

**Issue by grupot3** [andreasBihlmaier/gazebo2rviz#14]
I'd like to use this package with the following world (I've changed the extension to .txt to be able to upload it here, but it should be .world):
[forest.txt](https://github.com/andreasBihlmaier/gazebo2rviz/files/3117670/forest.txt)

But in Rviz only the tf appear, and not the markers:
![image](https://user-images.githubusercontent.com/13998651/56748496-f742be80-674d-11e9-9e1d-1537a3da6522.png)

I get the error `[INFO] [1556205619.112867, 216.026000]: Unable to load model: 246
Could not resolve modelname=247 to its SDF file
` for all of the cylinders

Ubuntu: 16.04
ROS: Kinetic

Thanks!

**Comment by CesMak** [comment]
I also would like to use this great package, but I have exactly the same error. Moreover my tf's do not move even though they move in Gazebo.

**Comment by CesMak** [comment]
I have the same problem:
I generate and launch my stls via urdf and xacro, where do I have to put my sdf, how should I load this?

**Comment by andreasBihlmaier** [comment]
https://github.com/andreasBihlmaier/gazebo2rviz/commit/06e5016b302368a5e7961a56cdef00c48a1f13a1 should add the requested feature:
`roslaunch gazebo2rviz gazebo2rviz.launch worldfile:=${PWD}/forest.world`

![Screenshot_20200512_134046](https://user-images.githubusercontent.com/6390551/81684340-2b6f4700-9457-11ea-8a10-e5a6316030c4.png)

**Comment by rud2810** [comment]
Can we use this package in kinetic also ??
