### ISSUE TITLE
Can't find namespaces in rviz

### ISSUE THREAD

**Issue by KhanMar2019** [andreasBihlmaier/gazebo2rviz#15]
Hello!
I'm doing all as in tutorial:
gazebo (add new object)
rviz (add tf and marker)
roslaunch gazebo2rviz gazebo2rviz.launch

But I can't see those objects in rviz (no namespaces in rviz)
While running roslaunch gazebo2rviz gazebo2rviz.launch get this:

roslaunch gazebo2rviz gazebo2rviz.launch
... logging to /home/pdc-labor/.ros/log/c5afc4ec-ac87-11e9-861a-00bb60ad67bd/roslaunch-pdclabor-ThinkPad-E480-4456.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://pdclabor-ThinkPad-E480:44655/

SUMMARY
========

PARAMETERS
 * /gazebo2marker/ignore_submodels_of: 
 * /gazebo2tf/ignore_submodels_of: 
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /
    gazebo2marker (gazebo2rviz/gazebo2marker_node.py)
    gazebo2tf (gazebo2rviz/gazebo2tf_node.py)
    static_tf_pub_world_to_gazebo_world (tf2_ros/static_transform_publisher)

ROS_MASTER_URI=http://localhost:11311

process[static_tf_pub_world_to_gazebo_world-1]: started with pid [4473]
process[gazebo2tf-2]: started with pid [4474]
process[gazebo2marker-3]: started with pid [4479]
[INFO] [1563803540.486203]: Ignoring submodels of: ['']
[INFO] [1563803540.503639]: Spinning
[INFO] [1563803540.555036]: Ignoring submodels of: ['']
[ERROR] [1563803540.556869]: ignore_submodels_of is currently not supported and will thus have no effect
[INFO] [1563803540.571319]: Spinning

**Comment by andreasBihlmaier** [comment]
It seems gazebo was not started with the ROS plugins. Please first run `roscore`. Then, try running gazebo via `roslaunch gazebo_ros empty_world.launch`

Please also provide the output of `rostopic list` and `rosnode info gazebo2marker gazebo2tf` while all nodes are running.

**Comment by KhanMar2019** [comment]
Thank you - it helped! Now it's working :)

But I have the issue with the second tutorial on your page - Open-Source Workflow to Create Geometrically and Visually Accurate Gazebo Models
I converted my .obj file to .dae file but can't upload it to Gazebo.
An I right that I need the .urdf file for this and then launch it?
Can you please give me the example of how you did it to open your .dae model?
The idea is that I need to open it in Gazebo and at the same time in Rviz.

Thank you!

**Comment by andreasBihlmaier** [comment]
@KhanMar2019 good that the tool works for you.

Let's move the other discussion to email or the blog comments :)
