### ISSUE TITLE
Error resource not found

### ISSUE THREAD

**Issue by lucasantoro** [andreasBihlmaier/gazebo2rviz#17]
Good evening,
sorry for my ignorance, but i receive "resource not found: gazebo2rviz".
How can i solve this problem?
thank you very much for your time and consideration

**Comment by andreasBihlmaier** [comment]
It sounds like you did either not properly build gazebo2rviz in a catkin workspace or did not source the catkin setup.bash after building.

Please provide further information on your setup and what commands you are executing when the error occurs.
