### ISSUE TITLE
Only a box appeared for each object

### ISSUE THREAD

**Issue by beatrizleon** [andreasBihlmaier/gazebo2rviz#4]
I am trying to use this package to import our scenes from gazebo to rviz. I am able to see all objects with transforms and if I move them, they are also correctly moved in rviz. However I am only seeing one box per  object, not the complete mesh. Here is an example of a simple scene:
![image](https://cloud.githubusercontent.com/assets/12493239/18842144/b75f24a2-83d9-11e6-89ae-3ec14263a995.png)
In the example provided by the package I see that the same table is correctly displayed. am I doing something wrong?

I see that @peci1, in one of the latest PRs (https://github.com/andreasBihlmaier/gazebo2rviz/pull/3), mentioned the same issue as well. I was wandering if he managed to solve it.

**Comment by peci1** [comment]
Not yet, but it's still on my list :)

**Comment by beatrizleon** [comment]
do you know what is the problem? and where?

@andreasBihlmaier how did you manage to show them in your example?
This a screenshot of the marker plugin in rviz:
![image](https://cloud.githubusercontent.com/assets/12493239/18844172/be9fb260-83e1-11e6-8059-4db6e602cdbd.png)

I see that it is different from the one in the example as it has the "_link" added. Also it has an issue with the ground plane as you can see.

**Comment by peci1** [comment]
The problem is multiple visual/collision elements per link aren't supported by pysdf yet. If you instead create multiple links, each with one visual/collision, it's okay.
